'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');const {EventEmitter}=require('node:events');
const root=path.resolve(__dirname,'..');
function load(relative, overrides={},globals={},cache=new Map()) {
 if(cache.has(relative)) return cache.get(relative).exports;
 const module={exports:{}};cache.set(relative,module);
 const code=ts.transpileModule(fs.readFileSync(path.join(root,relative),'utf8'),{fileName:relative,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
 vm.runInNewContext(code,{module,exports:module.exports,Buffer,URL,URLSearchParams,AbortSignal,Response,Date,console,setTimeout,clearTimeout,setInterval,clearInterval,process:{env:{}},require(name){if(Object.hasOwn(overrides,name))return overrides[name];if(name==='crypto')return require('node:crypto');if(name.startsWith('.'))return load(path.normalize(path.join(path.dirname(relative),name+'.ts')),overrides,globals,cache);throw new Error('Unexpected dependency '+name)},...globals},{filename:relative});return module.exports;
}
const dir='src/api/integrations/channel/findhub/services/';
const policy=load(dir+'findhub-tracking.policy.ts');const now=Date.now();const position={deviceId:'one',googleDeviceId:'g',latitude:-12,longitude:-39,timestamp:new Date(now-1000).toISOString(),source:'GOOGLE_DIRECT',ownReport:true};
test('independent interval, timeout and history retention boundaries',()=>{const s=policy.trackingSettings({intervalSeconds:30,timeoutMs:90000,historyEnabled:true,retentionDays:0});assert.equal(s.retentionDays,0);assert.equal(s.timeoutMs,90000);assert.equal(s.intervalSeconds,30)});
for(const values of [{intervalSeconds:-1},{intervalSeconds:0.5},{intervalSeconds:100000},{timeoutMs:4999},{timeoutMs:120001},{retentionDays:-1},{historyEnabled:'true'}])test('invalid tracking settings are refused '+JSON.stringify(values),()=>assert.throws(()=>policy.trackingSettings(values)));
test('a recent position does not invent an online state',()=>{assert.equal(policy.locationAvailability(position,300,null,now),'recent');assert.equal(policy.locationAvailability(position,300,'online',now),'online');assert.equal(policy.locationAvailability(position,300,'offline',now),'offline')});
test('missing, old, malformed and future coordinates handled truthfully',()=>{assert.equal(policy.locationAvailability(null,300),'no_location');assert.equal(policy.locationAvailability({...position,timestamp:new Date(now-600000).toISOString()},300,null,now),'stale');for(const v of [{latitude:91},{longitude:181},{timestamp:'bad'},{timestamp:new Date(now+600001).toISOString()}])assert.equal(policy.validPosition({...position,...v},now),false)});
test('position identity stable and source-aware',()=>{assert.equal(policy.positionFingerprint(position),policy.positionFingerprint({...position}));assert.notEqual(policy.positionFingerprint(position),policy.positionFingerprint({...position,longitude:-40}))});
function clientHarness(handler) {
 const calls=[];const sockets=[];const env={TRACCAR_ENABLED:'true',TRACCAR_MODE:'internal',TRACCAR_ADMIN_EMAIL:'admin@example.invalid',TRACCAR_ADMIN_PASSWORD:'test-only-secret',TRACCAR_ALLOWED_ORIGINS:'https://external.example.invalid,https://receiver.example.invalid'};
 class Socket extends EventEmitter{constructor(url,options){super();this.url=url;this.options=options;sockets.push(this)}close(){this.emit('close')}terminate(){this.emit('close')}}
 const exports=load(dir+'traccar-client.ts',{'ws':Socket},{process:{env},fetch:async(url,options)=>{calls.push({url,options});return handler(url,options)}});
 return {...exports,calls,sockets,env};
}
const json=(data,headers={})=>new Response(JSON.stringify(data),{status:200,headers:{'content-type':'application/json',...headers}});
test('disabled Traccar does not require URL, credentials or network',()=>{const h=clientHarness(()=>{throw Error('unexpected network')});h.env.TRACCAR_ENABLED='false';new h.TraccarClient({mode:'disabled'});assert.equal(h.calls.length,0);assert.throws(()=>new h.TraccarClient({mode:'internal'}))});
test('destinations reject unknown origins, redirect payloads and URL credentials',()=>{const h=clientHarness();for(const url of ['http://169.254.169.254','https://evil.invalid','https://user:pass@external.example.invalid','https://external.example.invalid/path','https://external.example.invalid/?token=x'])assert.throws(()=>h.traccarDestination(url));assert.equal(h.traccarDestination('https://external.example.invalid').origin,'https://external.example.invalid')});
test('internal URL is automatic and secrets are only sent on backend session request',async()=>{const h=clientHarness(()=>json({id:1},{'set-cookie':'JSESSIONID=test-cookie; Path=/; HttpOnly'}));const client=new h.TraccarClient({mode:'internal'});await client.session();assert.equal(h.calls[0].url,'http://traccar:8082/api/session');assert.equal(h.calls[0].options.redirect,'error');assert.equal(new URLSearchParams(h.calls[0].options.body).get('password'),'test-only-secret');client.close()});
test('external token becomes official session, not socket URL',async()=>{const h=clientHarness(()=>json({id:1},{'set-cookie':'JSESSIONID=private; HttpOnly'}));const client=new h.TraccarClient({mode:'external',url:'https://external.example.invalid',receiverUrl:'https://receiver.example.invalid',token:'private-token'});client.start(async()=>{},()=>{});await new Promise(r=>setTimeout(r,5));assert.equal(h.sockets.length,1);assert.equal(String(h.sockets[0].url),'wss://external.example.invalid/api/socket');assert.equal(h.sockets[0].options.headers.Cookie,'JSESSIONID=private');assert.equal(String(h.sockets[0].url).includes('private-token'),false);client.close()});
test('provisioning is stable per account/device and rejects another owner',async()=>{let expected;const h=clientHarness((url,options)=>options.method==='POST'?json({id:8,...JSON.parse(options.body)}):json([]));const client=new h.TraccarClient({mode:'internal'});expected=h.traccarUniqueId('a','one');const d=await client.provision('a','one','Phone');assert.equal(d.uniqueId,expected);assert.notEqual(expected,h.traccarUniqueId('b','one'));assert.equal(JSON.parse(h.calls[1].options.body).attributes.connectInstanceId,'a');client.close();const bad=clientHarness(()=>json([{id:1,uniqueId:expected,attributes:{connectInstanceId:'other'}}]));await assert.rejects(new bad.TraccarClient({mode:'internal'}).provision('a','one','Phone'),/não pertence/)});
test('positions use OsmAnd seconds, not nonexistent REST POST positions',async()=>{const h=clientHarness(()=>new Response(null,{status:200}));await new h.TraccarClient({mode:'internal'}).send('stable-id',position);assert.equal(h.calls[0].url,'http://traccar:5055');const f=new URLSearchParams(h.calls[0].options.body);assert.equal(f.get('timestamp'),String(Date.parse(position.timestamp)/1000));assert.equal(f.get('lat'),'-12');assert.equal(h.calls[0].options.redirect,'error')});
function response(){const res=new EventEmitter();Object.assign(res,{headersSent:false,writableEnded:false,destroyed:false,writableLength:0,frames:[],status(){return this},set(h){this.headers=h;return this},flushHeaders(){this.headersSent=true},write(x){this.frames.push(x);return true},end(){this.writableEnded=true;this.emit('close')}});return res}
const {findHubStream}=load(dir+'findhub-stream.ts');
test('SSE snapshot and instance events; GET body completion does not close stream',async()=>{const res=response();let listener,stopped=0;await findHubStream({params:{instanceName:'account'},destroyed:true,aborted:false},res,{subscribe(name,fn){assert.equal(name,'account');listener=fn;return()=>stopped++},async snapshot(name){return {instanceId:'account'}}});assert.equal(res.headers['X-Accel-Buffering'],'no');assert.equal(res.writableEnded,false);listener({event:'location',instanceId:'account'});assert.equal(res.frames.length,2);res.emit('close');assert.equal(stopped,1);listener({event:'ignored'});assert.equal(res.frames.length,2)});
test('SSE failed authorization/snapshot releases resources before any headers',async()=>{const res=response();let stopped=0;await assert.rejects(findHubStream({params:{instanceName:'x'}},res,{subscribe(){return()=>stopped++},async snapshot(){throw Error('denied')}}));assert.equal(stopped,1);assert.equal(res.headersSent,false)});
test('slow SSE reader is disconnected without unbounded buffer',async()=>{const res=response();let listener,stopped=0;await findHubStream({params:{instanceName:'account'}},res,{subscribe(n,fn){listener=fn;return()=>stopped++},async snapshot(){return {instanceId:'account'}}});res.writableLength=300000;listener({event:'large'});assert.equal(res.writableEnded,true);assert.equal(stopped,1)});

function runtimeHarness(globals={}) {
 const emitter=new EventEmitter(), events=[], calls=[], positions=[];
 const row={id:'d-a',instanceId:'a',accountId:'a',googleDeviceId:'g-a',name:'Phone',identifierType:'ANDROID',deviceType:'PHONE',trackingIntervalSeconds:60,trackingEnabled:false,latestPosition:null,lastLocationAt:null};
 const other={...row,id:'d-b',instanceId:'b',googleDeviceId:'g-b'};const devices=[row,other];
 const account={id:'account-a',instanceId:'a',googleEmail:'a@example.invalid',trackingSettings:{intervalSeconds:60,timeoutMs:30000,staleAfterSeconds:300,historyEnabled:true,retentionDays:30},encryptedTraccar:null};
 function match(r,w){return Object.entries(w||{}).every(([k,v])=>{if(k==='OR')return v.some(x=>match(r,x));if(v && typeof v==='object'){if('in' in v)return v.in.includes(r[k]);if('lt' in v)return r[k]<v.lt;if('lte' in v)return r[k]<=v.lte;if('equals' in v)return r[k]==null;}return r[k]===v})}
 const db={instance:{async update(){}},findHubAccount:{async findUnique({where}){assert.equal(where.instanceId,'a');return account},async update({where,data}){assert.equal(where.instanceId,'a');Object.assign(account,data);return account}},
  findHubDevice:{async findFirst({where}){calls.push(['device',where]);return devices.find(d=>match(d,where))},async findMany({where}){return devices.filter(d=>match(d,where))},async updateMany({where,data}){calls.push(['update',where]);let n=0;for(const d of devices)if(match(d,where)){Object.assign(d,data);n++}return {count:n}},async update({where,data}){const d=devices.find(d=>d.id===where.id);Object.assign(d,data);return d}},
  findHubPosition:{async count(){return positions.length},async upsert({where,create}){calls.push(['history',where]);let old=positions.find(p=>p.fingerprint===create.fingerprint&&p.instanceId===create.instanceId&&p.deviceId===create.deviceId);if(!old){old={id:'p-'+positions.length,...create};positions.push(old)}return old},async findMany({where,take}){calls.push(['history-read',where]);return positions.filter(p=>match(p,where)).slice(0,take)},async deleteMany({where}){calls.push(['history-delete',where]);let n=0;for(let i=positions.length-1;i>=0;i--)if(match(positions[i],where)){positions.splice(i,1);n++}return {count:n}}},
  findHubTraccarBinding:{async findUnique(){return null},async findMany({where}){assert.equal(where.instanceId,'a');return []}},async $transaction(fn){return fn(db)}};
 const overrides={
  '@prisma/client':{Prisma:{DbNull:{isNull:true}}},'@api/server.module':{eventManager:{async emit(e){events.push(e)}}},'@config/logger.config':{Logger:class{setInstance(){}error(){}}},
  '../auth/findhub-auth-broker.service':{FindHubAuthBrokerService:class{}},'../auth/findhub-credential-vault':{FindHubCredentialVault:class{encrypt(v){return JSON.stringify(v)}decrypt(v){return JSON.parse(v)}}},
  './findhub-protocol.client':{FindHubProtocolClient:class{}},'./findhub-traccar.service':{FindHubTraccarService:class{async send(){}}},
  './traccar-client':{TraccarClient:class{close(){}start(fn,state){state('connected')}},resolveTraccarConnection:c=>c,traccarDestination:v=>new URL(v)},
 };
 const {FindHubStartupService}=load(dir+'findhub-runtime.service.ts',overrides,globals);
 const runtime=new FindHubStartupService({get(){return {URL:'https://connect.example.invalid'}}},emitter,db);
 runtime.setInstance({instanceName:'account-a',instanceId:'a',token:'private-api-key'});runtime.stateConnection={state:'open'};runtime.protocol={ready:true,async close(){},async locate(){return []}};
 return {runtime,db,row,other,positions,events,calls,emitter,account};
}
test('runtime refuses a device belonging to a different account',async()=>{const h=runtimeHarness();await assert.rejects(h.runtime.device('d-b'),/not found/);assert.equal(h.calls[0][1].instanceId,'a')});
test('history is deduplicated and scoped; last position never regresses',async()=>{const h=runtimeHarness(),d=await h.runtime.device('d-a'),p={...position,deviceId:d.id,googleDeviceId:d.googleDeviceId};await h.runtime.persistPosition(d,p);await h.runtime.persistPosition(d,p);assert.equal(h.positions.length,1);const older={...p,timestamp:new Date(now-50000).toISOString(),latitude:-13};await h.runtime.persistPosition(d,older);assert.equal(h.row.latestPosition.latitude,p.latitude);assert.equal(h.positions.length,2);assert.equal(h.other.latestPosition,null);assert.ok(h.calls.filter(c=>c[0]==='update').every(c=>c[1].instanceId==='a'))});
test('disabled historian keeps last position but adds no historical row',async()=>{const h=runtimeHarness();h.account.trackingSettings.historyEnabled=false;await h.runtime.persistPosition(await h.runtime.device('d-a'),position);assert.equal(h.positions.length,0);assert.equal(h.row.latestPosition.latitude,position.latitude)});
test('retention 0 preserves all history; positive retention never deletes another account',async()=>{const h=runtimeHarness();h.account.trackingSettings.retentionDays=0;assert.equal(await h.runtime.pruneHistory(),0);h.account.trackingSettings.retentionDays=1;h.runtime.options=undefined;h.positions.push({id:'old-a',instanceId:'a',deviceId:'d-a',recordedAt:new Date(now-172800000)},{id:'old-b',instanceId:'b',deviceId:'d-b',recordedAt:new Date(now-172800000)});assert.equal(await h.runtime.pruneHistory(),1);assert.equal(h.positions[0].instanceId,'b')});
test('runtime SSE subscription does not receive other account events or API credentials',async()=>{const h=runtimeHarness(),seen=[];const stop=h.runtime.subscribe(e=>seen.push(e));h.emitter.emit('findhub:stream:b',{instanceId:'b'});await h.runtime.emit('findhub.location.updated',{location:position});assert.equal(seen.length,1);assert.equal(seen[0].instanceId,'a');assert.ok(!JSON.stringify(seen).includes('private-api-key'));stop();await h.runtime.emit('findhub.error',{});assert.equal(seen.length,1)});
test('history query checks device ownership before reading rows',async()=>{const h=runtimeHarness();await assert.rejects(h.runtime.positions('d-b'));assert.equal(h.calls.filter(c=>c[0]==='history-read').length,0)});
test('settings use an allowlist, never exposing or accepting credential fields',async()=>{const h=runtimeHarness();await assert.rejects(h.runtime.saveSettings({token:'bad'}));const saved=await h.runtime.saveSettings({retentionDays:0});assert.equal(saved.retentionDays,0);assert.equal(h.account.trackingSettings.retentionDays,0)});
test('snapshot reports verified status, real counters, settings and no provider credentials',async()=>{const h=runtimeHarness();const result=await h.runtime.snapshot();assert.equal(result.connected,true);assert.equal(result.devices.length,1);assert.equal(result.counts.devices,1);assert.equal(result.email,'a@example.invalid');assert.equal(result.traccar.mode,'disabled');assert.ok(!JSON.stringify(result).includes('private-api-key'))});


test('manual locate honors its timeout without enabling tracking',async()=>{const h=runtimeHarness();let selected;h.runtime.protocol={locate:async(d,t)=>{selected=t;return []}};await h.runtime.locate('d-a',90000);assert.equal(selected,90000);assert.equal(h.row.trackingEnabled,false);await assert.rejects(h.runtime.locate('d-a',0));});
test('metadata-only push does not consume a pending location request',async()=>{
 const requestId='request-test';let report=false,resolved=0,cleared=0;
 const fake={decodeDeviceUpdate:()=>({requestUuid:requestId,deviceMetadata:Buffer.from('metadata')}),decodeLocationReports:()=>report?[{encryptedLocation:Buffer.from('ciphertext')}]:[]};
 const {FindHubProtocolClient}=load(dir+'findhub-protocol.client.ts',{'../auth/google-play-auth.client':{},'../crypto/findhub-crypto':{},'../protocol/fcm.client':{},'../protocol/findhub-proto':fake,'../protocol/nova.client':{},'../protocol/spot.client':{}},{clearTimeout:()=>cleared++});
 const client=Object.create(FindHubProtocolClient.prototype);client.pending=new Map([[requestId,{timer:1,resolve:()=>resolved++}]]);
 client.handlePushPayload(Buffer.alloc(0));assert.equal(client.pending.size,1);assert.equal(resolved,0);
 report=true;client.handlePushPayload(Buffer.alloc(0));assert.equal(client.pending.size,0);assert.equal(resolved,1);assert.equal(cleared,1);
});

for (const intervalSeconds of [0,1,2,15,30,60,86400]) test('requested interval survives validation: '+intervalSeconds,()=>{assert.equal(policy.trackingSettings({intervalSeconds}).intervalSeconds,intervalSeconds);assert.equal(policy.trackingDelayMs(intervalSeconds),intervalSeconds*1000)});
test('legacy env recommendation cannot override explicit zero',()=>{const p=load(dir+'findhub-tracking.policy.ts',{}, {process:{env:{FINDHUB_MIN_TRACKING_INTERVAL_SECONDS:'30'}}});assert.equal(p.trackingMinimum(),0);assert.equal(p.trackingSettings({intervalSeconds:0}).intervalSeconds,0)});
test('zero interval retries yield and back off after failures',()=>{assert.equal(policy.trackingDelayMs(0,1),2000);assert.equal(policy.trackingDelayMs(0,4),16000);assert.equal(policy.trackingDelayMs(2,0),2000)});

test('zero tracking persists, restores and never overlaps a pending request',async()=>{
 const timers=[];const h=runtimeHarness({setTimeout(fn,delay){const timer={fn,delay,unref(){}};timers.push(timer);return timer},clearTimeout(){}});
 let release,calls=0;h.runtime.locate=async()=>{calls++;return await new Promise(r=>release=r)};
 await h.runtime.startTracking('d-a',0,30000);assert.equal(h.row.trackingIntervalSeconds,0);assert.equal(timers[0].delay,0);
 const running=timers[0].fn();await Promise.resolve();assert.equal(calls,1);assert.equal(timers.length,1);
 release(position);await running;assert.equal(timers[1].delay,0);
 await h.runtime.stopTracking('d-a');await timers[1].fn();assert.equal(calls,1);
 h.row.trackingEnabled=true;await h.runtime.restoreTracking();assert.equal(timers.at(-1).delay,0);
});
