import fs from 'node:fs';

const read = (path) => fs.readFileSync(path, 'utf8');
const assert = (condition, message) => {
  if (!condition) throw new Error(message);
};

const zapo = read('src/api/integrations/channel/whatsapp/zapo.whatsapp.service.ts');
const zapoExtensions = read('src/api/integrations/channel/whatsapp/zapo.provider.extensions.ts');
const zapoAccountExtensions = read('src/api/integrations/channel/whatsapp/zapo.provider.account.extensions.ts');
const channelController = read('src/api/integrations/channel/channel.controller.ts');
const baileys = read('src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts');
const instanceController = read('src/api/controllers/instance.controller.ts');
const callController = read('src/api/controllers/call.controller.ts');
const callRouter = read('src/api/routes/call.router.ts');
const voiceMedia = read('src/api/services/voice-media.service.ts');
const packageJson = JSON.parse(read('package.json'));

assert(zapo.includes('class ZapoStartupService'), 'Native Zapo startup service is missing');
assert(zapo.includes("Integration.WHATSAPP_ZAPO"), 'Zapo provider integration identifier is missing');
assert(zapo.includes('public async offerCall'), 'Zapo voice offerCall implementation is missing');
assert(zapo.includes('public async listCalls'), 'Zapo voice listCalls implementation is missing');
assert(zapo.includes("this.client.on('voip_call_incoming'"), 'Zapo incoming-call listener is missing');
assert(zapo.includes("this.client.on('voip_call_inbound_audio'"), 'Zapo inbound audio hook is missing');
assert(zapo.includes("rawRemoteJid.endsWith('@lid')"), 'Zapo LID-to-PN canonicalization is missing');
assert(zapo.includes("authMode: 'qrcode' | 'pairing-code'"), 'Zapo QR/pairing mode isolation is missing');
assert(zapo.includes('resetLinkingClient'), 'Zapo stale linking-client reset is missing');
assert(zapo.includes('ZAPO_PAIRING_DEVICE_OS'), 'Zapo stable pairing fingerprint is missing');
assert(zapo.includes("this.configService.get<QrCode>('QRCODE').COLOR"), 'Zapo must use the shared QR color');
assert(zapo.includes('WHATSAPP_PROTOCOL_BROWSER_CLIENT'), 'Zapo must inherit the shared Connect|API QR device label');
assert(instanceController.includes('authenticationQueues'), 'Per-instance WhatsApp authentication serialization is missing');
assert(instanceController.includes('withAuthenticationLock'), 'Shared WhatsApp authentication lock is missing');
assert(instanceController.includes('normalizeQrCode'), 'Provider-neutral QR normalization is missing');
assert(instanceController.includes("get<QrCode>('QRCODE').AUTH_TIMEOUT_MS"), 'Shared WhatsApp auth timeout is missing');
assert(baileys.includes("const pairingCodeBrowser: WABrowserDescription = ['Ubuntu', 'Chrome', '20.0.04']"), 'Stable Baileys pairing fingerprint changed unexpectedly');
assert(callController.includes("this.method(instanceName, 'offerCall')"), 'Provider-neutral call delegation is missing');
assert(callRouter.includes("this.routerPath('list')"), 'Call list route is missing');
assert(voiceMedia.includes("VOICE_MEDIA_PATH = '/voice/media'"), 'Dedicated voice media gateway is missing');
assert(voiceMedia.includes('feedLiveAudio'), 'Browser-to-provider voice media bridge is missing');
assert(voiceMedia.includes('onInboundVoiceAudio'), 'Provider-to-browser voice media bridge is missing');
assert(packageJson.dependencies?.['@innovatorssoft/zapo-js'] === '1.6.3', 'Zapo JS version must stay pinned at 1.6.3');
assert(packageJson.dependencies?.['@innovatorssoft/voip'] === '1.0.0', 'Zapo VoIP version must stay pinned at 1.0.0');
assert(packageJson.dependencies?.['zapo-js'] === 'npm:@innovatorssoft/zapo-js@1.6.3', 'Legacy zapo-js runtime alias is missing');

assert(channelController.includes('ZapoAccountStartupService'), 'Zapo account compatibility layer is not wired');
assert(zapoExtensions.includes("client.on('presence'"), 'Zapo presence listener is missing');
assert(zapoExtensions.includes("client.on('chatstate'"), 'Zapo chatstate listener is missing');
assert(zapoExtensions.includes("client.on('app_state_mutation'"), 'Zapo app-state mutation listener is missing');
assert(zapoExtensions.includes("client.on('mutation_send'"), 'Zapo outbound mutation listener is missing');
assert(zapoExtensions.includes("schema: 'LabelJid'"), 'Zapo label association mutation is missing');
assert(zapoExtensions.includes("schema: 'LabelEdit'"), 'Zapo label edit mutation parsing is missing');
assert(zapoExtensions.includes('public async fetchLabels'), 'Zapo label listing compatibility is missing');
assert(zapoExtensions.includes('public async handleLabel'), 'Zapo label mutation compatibility is missing');
assert(zapoExtensions.includes('public async whatsappNumber'), 'Zapo registration lookup compatibility is missing');
assert(zapoExtensions.includes('getLidsByPhoneNumbers'), 'Zapo registration lookup must use native LID usync');
assert(zapoExtensions.includes('public async profilePicture'), 'Zapo profile-picture hardening is missing');

assert(zapoAccountExtensions.includes('public async markMessageAsRead'), 'Zapo read-receipt compatibility is missing');
assert(zapoAccountExtensions.includes("sendReceipt(jid, ids, { type: 'read' })"), 'Zapo read receipts must use native receipt API');
assert(zapoAccountExtensions.includes('public async archiveChat'), 'Zapo archive/unarchive compatibility is missing');
assert(zapoAccountExtensions.includes('chat.setChatArchive'), 'Zapo archive must use the public app-state coordinator');
assert(zapoAccountExtensions.includes('public async markChatUnread'), 'Zapo mark-unread compatibility is missing');
assert(zapoAccountExtensions.includes('chat.setChatRead(jid, false)'), 'Zapo mark-unread must use the public app-state coordinator');
assert(zapoAccountExtensions.includes('public async deleteMessage'), 'Zapo message revoke compatibility is missing');
assert(zapoAccountExtensions.includes("type: 'revoke'"), 'Zapo message deletion must use the native revoke message type');
assert(zapoAccountExtensions.includes('Events.MESSAGES_DELETE'), 'Zapo delete webhook parity is missing');
assert(zapoAccountExtensions.includes('public async updateMessage'), 'Zapo message edit compatibility is missing');
assert(zapoAccountExtensions.includes('editKey:'), 'Zapo message edit must use the native editKey option');
assert(zapoAccountExtensions.includes('Events.MESSAGES_UPDATE'), 'Zapo edit webhook parity is missing');
assert(zapoAccountExtensions.includes("status: 'EDITED'"), 'Zapo local edited-message state is missing');
assert(zapoAccountExtensions.includes("status: 'DELETED'"), 'Zapo local deleted-message state is missing');
assert(zapoAccountExtensions.includes('public async fetchPrivacySettings'), 'Zapo privacy read compatibility is missing');
assert(zapoAccountExtensions.includes('public async updatePrivacySettings'), 'Zapo privacy write compatibility is missing');
assert(zapoAccountExtensions.includes("setPrivacySetting('profilePicture'"), 'Zapo profile privacy mapping is missing');
assert(zapoAccountExtensions.includes('public async updateProfileName'), 'Zapo profile-name update is missing');
assert(zapoAccountExtensions.includes('profile.setPushName'), 'Zapo profile name must use the public coordinator');
assert(zapoAccountExtensions.includes('public async updateProfileStatus'), 'Zapo profile-status update is missing');
assert(zapoAccountExtensions.includes('profile.setStatus'), 'Zapo profile status must use the public coordinator');
assert(zapoAccountExtensions.includes('public async updateProfilePicture'), 'Zapo profile-picture update is missing');
assert(zapoAccountExtensions.includes('profile.setProfilePicture'), 'Zapo profile picture must use the public coordinator');
assert(zapoAccountExtensions.includes('public async removeProfilePicture'), 'Zapo profile-picture removal is missing');
assert(zapoAccountExtensions.includes('profile.deleteProfilePicture'), 'Zapo profile removal must use the public coordinator');
assert(zapoAccountExtensions.includes('public async blockUser'), 'Zapo block/unblock compatibility is missing');
assert(zapoAccountExtensions.includes('privacy.blockUser'), 'Zapo block must use the LID-aware privacy coordinator');
assert(zapoAccountExtensions.includes('privacy.unblockUser'), 'Zapo unblock must use the LID-aware privacy coordinator');

console.log('Zapo provider invariants: OK');
