use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn emit_agent(out: &mut String, const_name: &str, file: &Path) {
    if file.is_file() {
        let absolute = file.canonicalize().expect("canonicalize embedded agent");
        out.push_str(&format!(
            "pub static {const_name}: &[u8] = include_bytes!(r#\"{}\"#);\n",
            absolute.display()
        ));
    } else {
        out.push_str(&format!("pub static {const_name}: &[u8] = &[];\n"));
    }
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let embedded = manifest.join("embedded");
    println!("cargo:rerun-if-changed={}", embedded.display());

    if env::var("PROFILE").as_deref() == Ok("release") {
        for name in ["agent-linux-amd64", "agent-linux-arm64"] {
            let file = embedded.join(name);
            assert!(file.is_file() && fs::metadata(&file).unwrap().len() > 4,
                    "Release requires both static Linux agents: {name}");
        }
    }
    println!("cargo:rerun-if-changed=build-info.json");
    let mut generated = String::new();
    generated.push_str("// Generated by src-tauri/build.rs.\n");
    emit_agent(&mut generated, "AGENT_LINUX_AMD64", &embedded.join("agent-linux-amd64"));
    emit_agent(&mut generated, "AGENT_LINUX_ARM64", &embedded.join("agent-linux-arm64"));

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_agents.rs");
    fs::write(out, generated).expect("write embedded_agents.rs");
    tauri_build::build();
}
