<script setup lang="ts">
import { onMounted, ref } from 'vue'; import AppShell from '@/layouts/AppShell.vue'; import PageHeader from '@/components/PageHeader.vue'; import EmptyState from '@/components/EmptyState.vue'; import { connect } from '@/services/connect'; import { friendlyError } from '@/services/errors'; import type { ConnectionItem,Conversation,Message } from '@/types/domain'
const instances=ref<ConnectionItem[]>([]),selectedInstance=ref(''),chats=ref<Conversation[]>([]),selectedChat=ref<Conversation|null>(null),messages=ref<Message[]>([]),draft=ref(''),error=ref('')
async function loadChats(){selectedChat.value=null;messages.value=[];if(!selectedInstance.value)return;try{chats.value=await connect.conversations(selectedInstance.value)}catch(e){error.value=friendlyError(e)}}
async function openChat(chat:Conversation){selectedChat.value=chat;messages.value=await connect.messages(selectedInstance.value,chat.rawRef||chat.id).catch(()=>[])}
async function send(){if(!draft.value.trim()||!selectedChat.value)return; const number=(selectedChat.value.rawRef||selectedChat.value.subtitle||'').split('@')[0]; await connect.sendText(selectedInstance.value,number,draft.value); draft.value=''; await openChat(selectedChat.value)}
onMounted(async()=>{instances.value=await connect.connections().catch(()=>[]);selectedInstance.value=instances.value[0]?.id||'';await loadChats()})
</script>
<template><AppShell><PageHeader title="Conversas" description="Acompanhe atendimentos e mensagens em um só lugar."/><div v-if="error" class="alert error">{{error}}</div><div class="conversation-shell"><aside class="conversation-list"><select v-model="selectedInstance" class="select" @change="loadChats"><option v-for="i in instances" :key="i.id" :value="i.id">{{i.name}}</option></select><button v-for="chat in chats" :key="chat.id" class="conversation-row" :class="{active:selectedChat?.id===chat.id}" @click="openChat(chat)"><span class="avatar">{{chat.title.slice(0,1).toUpperCase()}}</span><div><strong>{{chat.title}}</strong><small>{{chat.lastMessage || chat.subtitle}}</small></div><b v-if="chat.unread">{{chat.unread}}</b></button><EmptyState v-if="!chats.length" title="Nenhuma conversa" description="As conversas deste canal aparecerão aqui."/></aside><section class="chat-panel"><template v-if="selectedChat"><header><span class="avatar">{{selectedChat.title.slice(0,1).toUpperCase()}}</span><div><strong>{{selectedChat.title}}</strong><small>{{selectedChat.subtitle}}</small></div></header><div class="message-list"><div v-for="m in messages" :key="m.id" class="message-bubble" :class="m.direction"><p>{{m.text}}</p><small>{{m.timestamp ? new Date(Number(m.timestamp)*1000 || m.timestamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}) : ''}}</small></div></div><form class="composer" @submit.prevent="send"><input v-model="draft" placeholder="Digite uma mensagem..."/><button class="btn primary">Enviar</button></form></template><EmptyState v-else icon="chat" title="Selecione uma conversa" description="Escolha uma conversa ao lado para visualizar as mensagens."/></section></div></AppShell></template>
