<script setup lang="ts">
import { onMounted, ref } from 'vue'
import AppShell from '@/layouts/AppShell.vue'; import PageHeader from '@/components/PageHeader.vue'; import MetricCard from '@/components/MetricCard.vue'; import PanelCard from '@/components/PanelCard.vue'; import StatusPill from '@/components/StatusPill.vue'; import SparkBars from '@/components/SparkBars.vue'; import SparkLine from '@/components/SparkLine.vue'; import AppIcon from '@/components/AppIcon.vue'; import { connect } from '@/services/connect'; import { friendlyError } from '@/services/errors'; import type { Overview } from '@/types/domain'
const data=ref<Overview|null>(null), error=ref('')
onMounted(async()=>{try{const [overview,audit]=await Promise.allSettled([connect.overview(),connect.audit()]); if(overview.status==='fulfilled') data.value={...overview.value,recent:audit.status==='fulfilled'?audit.value.slice(0,4).map(x=>({id:x.id,title:x.description,detail:x.actor,when:x.createdAt})):overview.value.recent}; else throw overview.reason}catch(e){error.value=friendlyError(e)}})
const fmt=(v:number)=>new Intl.NumberFormat('pt-BR').format(v||0)
const when=(value?:string)=>{if(!value)return 'Agora'; const d=new Date(value); if(Number.isNaN(d.getTime()))return String(value); const mins=Math.max(0,Math.round((Date.now()-d.getTime())/60000)); return mins<1?'Agora':mins<60?`Há ${mins} min`:`Há ${Math.round(mins/60)} h`}
</script>
<template><AppShell><PageHeader title="Visão Geral" description="Acompanhe sua operação em uma única tela."/><div v-if="error" class="alert error">{{error}}</div><div v-else-if="!data" class="skeleton-page"></div><template v-else><div class="metric-grid"><MetricCard icon="automation" title="Operação" :value="data.online?'Online':'Indisponível'" :hint="data.version?`v${data.version}`:''" accent="green"/><MetricCard icon="radio" title="Instâncias ativas" :value="`${data.connections.connected}/${data.connections.total}`" hint="conectadas"/><MetricCard icon="mail" title="Mensagens" :value="fmt(data.totals.messages)" hint="registradas" accent="cyan"/><MetricCard icon="chat" title="Conversas" :value="fmt(data.totals.conversations)" hint="registradas" accent="violet"/></div><div class="dashboard-layout"><div class="dashboard-main"><div class="chart-grid"><PanelCard title="Mensagens" description="Movimentação recente"><div class="chart-value">{{fmt(data.totals.messages)}}</div><SparkBars :values="data.trends?.messages"/></PanelCard><PanelCard title="Conversas ativas" description="Movimentação recente"><div class="chart-value">{{fmt(data.totals.conversations)}}</div><SparkLine :values="data.trends?.conversations"/></PanelCard></div><PanelCard title="Atividade recente"><div v-if="data.recent.length" class="activity-list"><div v-for="item in data.recent" :key="item.id" class="activity-item"><span class="activity-icon"><AppIcon name="chat" :size="17"/></span><div><strong>{{item.title}}</strong><small>{{item.detail}}</small></div><time>{{when(item.when)}}</time></div></div><div v-else class="muted-block">Nenhuma atividade recente.</div></PanelCard></div><aside class="dashboard-side"><PanelCard title="Status dos serviços"><div class="service-list"><div v-for="item in data.services" :key="item.key"><span>{{item.label}}</span><StatusPill :status="item.status"/></div></div></PanelCard><div class="all-good"><span><AppIcon name="automation" :size="30"/></span><div><strong>{{ data.online ? 'Tudo em funcionamento' : 'Atenção necessária' }}</strong><p>{{ data.online ? 'Sua operação está ativa e os serviços principais estão funcionando normalmente.' : 'Há um item que precisa de atenção.' }}</p></div></div></aside></div></template></AppShell></template>
