<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Building2, Plus, RefreshCw } from 'lucide-vue-next'
import { api, apiError } from '../api/client'

interface Partner { id:string; name:string; slug:string; status:string; hostname?:string|null; branding_mode:string; branding_profile_id?:string|null }
const items=ref<Partner[]>([]); const loading=ref(false); const error=ref(''); const creating=ref(false); const name=ref(''); const hostname=ref('')
async function load(){loading.value=true;error.value='';try{const r=await api.get('/control/v1/partners?per_page=100');items.value=r.data.data||[]}catch(e){error.value=apiError(e)}finally{loading.value=false}}
async function create(){if(!name.value.trim())return;creating.value=true;error.value='';try{await api.post('/control/v1/partners',{name:name.value,hostname:hostname.value||null});name.value='';hostname.value='';await load()}catch(e){error.value=apiError(e)}finally{creating.value=false}}
onMounted(load)
</script>
<template><section class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.15em] text-blue-600">Control Plane</p><h1 class="mt-1 text-2xl font-semibold text-slate-950">Partners</h1><p class="mt-1 text-sm text-slate-500">Partners podem usar a marca Connect|API ou publicar branding próprio; seus tenants herdam automaticamente.</p></div><button class="btn-secondary" @click="load"><RefreshCw :size="16"/>Atualizar</button></div><div v-if="error" class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{{error}}</div><div class="grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><form class="card space-y-4 p-5" @submit.prevent="create"><div class="flex items-center gap-2"><Building2 :size="18" class="text-blue-600"/><h2 class="font-semibold">Novo Partner</h2></div><div><label class="label">Nome</label><input v-model="name" class="input mt-1.5" required/></div><div><label class="label">Hostname opcional</label><input v-model="hostname" class="input mt-1.5" placeholder="partner.exemplo.com"/></div><button class="btn-primary w-full" :disabled="creating"><Plus :size="16"/>{{creating?'Criando…':'Criar Partner'}}</button></form><div class="card overflow-hidden"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold">Partners cadastrados</h2></div><div v-if="loading" class="p-6 text-sm text-slate-500">Carregando…</div><div v-else-if="!items.length" class="p-6 text-sm text-slate-500">Nenhum Partner cadastrado.</div><div v-else class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Partner</th><th class="px-4 py-3">Hostname</th><th class="px-4 py-3">Branding</th><th class="px-4 py-3">Status</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" class="border-t border-slate-100"><td class="px-4 py-3"><p class="font-semibold">{{item.name}}</p><p class="text-xs text-slate-400">{{item.slug}}</p></td><td class="px-4 py-3">{{item.hostname||'—'}}</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold" :class="item.branding_mode==='CUSTOM'?'bg-cyan-50 text-cyan-700':'bg-blue-50 text-blue-700'">{{item.branding_mode}}</span></td><td class="px-4 py-3">{{item.status}}</td></tr></tbody></table></div></div></div></section></template>
