[package]
name = "connect-deploy-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "connect-deploy-agent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
deployer-protocol = { path = "../deployer-protocol" }
dirs.workspace = true
fs2.workspace = true
hex.workspace = true
libc.workspace = true
percent-encoding.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
url.workspace = true
wait-timeout.workspace = true
uuid.workspace = true
zeroize.workspace = true
