<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Check, Clipboard, HandCoins, Plus } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import { fetchAllPages } from '../api/pagination'
import type { ApiResponse, Charge, Customer, Payment, Receivable } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'
import StatusBadge from '../components/StatusBadge.vue'
import SearchSelect, { type SearchSelectOption } from '../components/SearchSelect.vue'
import InlineAlert from '../components/InlineAlert.vue'

const charges=ref<Charge[]>([]),payments=ref<Payment[]>([]),receivables=ref<Receivable[]>([]),customers=ref<Customer[]>([]),error=ref(''),success=ref(''),modal=ref(false),copied=ref('')
const form=reactive({customer_id:'',receivable_id:'',charge_id:null as string|null,provider:'MANUAL',external_id:'',end_to_end_id:'',amount:'0.00',paid_at:new Date().toISOString().slice(0,16),payment_method:'TRANSFER'})
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const customer=(id:string)=>customers.value.find(item=>item.id===id)
const receivable=(id:string)=>receivables.value.find(item=>item.id===id)
const eligibleReceivables=computed(()=>receivables.value.filter(item=>Number(item.balance)>0&&!['PAID','CANCELLED','REVERSED'].includes(item.status)))
const customerOptions=computed<SearchSelectOption[]>(()=>[...new Set(eligibleReceivables.value.map(item=>item.customer_id))].map(id=>{const item=customer(id);return{value:id,label:item?.name||'Cliente',description:item?.tax_id||item?.trade_name||'',keywords:`${item?.name||''} ${item?.trade_name||''} ${item?.tax_id||''} ${item?.email||''} ${item?.whatsapp||''}`}}))
const receivableOptions=computed<SearchSelectOption[]>(()=>eligibleReceivables.value.filter(item=>!form.customer_id||item.customer_id===form.customer_id).map(item=>{const owner=customer(item.customer_id);return{value:item.id,label:`${owner?.name||'Cliente'} · ${money(item.balance)}`,description:`${item.document_number} · vence ${new Date(item.due_date+'T00:00:00').toLocaleDateString('pt-BR')}`,keywords:`${owner?.name||''} ${owner?.tax_id||''} ${item.document_number} ${item.description} ${item.balance}`}}))
const paymentMethodOptions:SearchSelectOption[]=[{value:'TRANSFER',label:'Transferência'},{value:'PIX',label:'Pix'},{value:'BOLETO',label:'Boleto'},{value:'CASH',label:'Dinheiro'}]
const chargeOrigin=(item:Charge)=>item.charge_type.includes('PIX')&&item.charge_type.includes('BOLETO')?'Boleto + Pix':item.charge_type==='PIX'?'Pix':item.charge_type==='BOLETO'?'Boleto':'Cobrança'
const paymentOrigin=(item:Payment)=>({TRANSFER:'Transferência',PIX:'Pix',BOLETO:'Boleto',CASH:'Dinheiro',CNAB:'Retorno bancário',CARD:'Cartão'} as Record<string,string>)[item.payment_method]||'Pagamento'

async function load(){error.value='';try{const [a,b,c,d]=await Promise.all([api.get<ApiResponse<Charge[]>>('/v1/charges'),api.get<ApiResponse<Payment[]>>('/v1/payments'),fetchAllPages<Receivable>('/v1/receivables'),fetchAllPages<Customer>('/v1/customers')]);charges.value=a.data.data;payments.value=b.data.data;receivables.value=c;customers.value=d}catch(e){error.value=apiError(e)}}
function openPayment(){const item=eligibleReceivables.value[0];Object.assign(form,{customer_id:item?.customer_id||'',receivable_id:item?.id||'',charge_id:null,provider:'MANUAL',external_id:`MANUAL-${Date.now()}`,end_to_end_id:'',amount:item?.balance||'0.00',paid_at:new Date().toISOString().slice(0,16),payment_method:'TRANSFER'});modal.value=true}
async function pay(){error.value='';try{await api.post('/v1/payments',{receivable_id:form.receivable_id,provider:'MANUAL',external_id:form.external_id,end_to_end_id:form.end_to_end_id||null,amount:Number(form.amount),paid_at:new Date(form.paid_at).toISOString(),payment_method:form.payment_method,charge_id:form.charge_id||null});modal.value=false;success.value='Pagamento registrado.';await load()}catch(e){error.value=apiError(e)}}
async function copy(value:string|undefined,key:string){if(!value)return;await navigator.clipboard.writeText(value);copied.value=key;setTimeout(()=>copied.value='',1500)}
watch(()=>form.customer_id,()=>{if(form.receivable_id&&!receivableOptions.value.some(option=>option.value===form.receivable_id))form.receivable_id=receivableOptions.value[0]?.value||''})
watch(()=>form.receivable_id,(id)=>{const item=receivable(id);if(item){form.customer_id=item.customer_id;form.amount=item.balance;const related=charges.value.find(charge=>charge.receivable_id===id&&charge.status!=='CANCELLED');form.charge_id=related?.id||null}})
onMounted(load)
</script>
<template>
<PageHeader title="Cobranças e pagamentos" subtitle="Boletos, Pix, liquidações e baixas financeiras."><button class="btn-primary" @click="openPayment"><Plus :size="18"/> Registrar pagamento</button></PageHeader>
<InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/>
<section><h2 class="mb-3 text-lg font-semibold">Cobranças emitidas</h2><div class="table-wrap"><table class="table"><thead><tr><th>Cliente / título</th><th>Tipo</th><th>Identificadores</th><th>Linha digitável / Pix</th><th>Status</th></tr></thead><tbody><tr v-for="item in charges" :key="item.id"><td><p class="font-semibold">{{customer(receivable(item.receivable_id)?.customer_id||'')?.name||'Cliente'}}</p><p class="text-xs text-slate-400">{{receivable(item.receivable_id)?.document_number||'Título financeiro'}}</p></td><td>{{chargeOrigin(item)}}</td><td><p class="text-xs">{{item.external_id}}</p><p class="text-xs text-slate-400">Nosso nº {{item.our_number||'—'}} · TXID {{item.txid||'—'}}</p></td><td class="max-w-md"><button v-if="item.digitable_line" class="mb-1 flex max-w-full items-center gap-2 text-left text-xs text-teal-700" @click="copy(item.digitable_line,item.id+'line')"><component :is="copied===item.id+'line'?Check:Clipboard" :size="14"/><span class="truncate">{{item.digitable_line}}</span></button><button v-if="item.pix_copy_paste" class="flex max-w-full items-center gap-2 text-left text-xs text-blue-700" @click="copy(item.pix_copy_paste,item.id+'pix')"><component :is="copied===item.id+'pix'?Check:Clipboard" :size="14"/><span class="truncate">Pix Copia e Cola</span></button></td><td><StatusBadge :status="item.status"/></td></tr><tr v-if="!charges.length"><td colspan="5" class="py-10 text-center text-slate-400">Nenhuma cobrança emitida.</td></tr></tbody></table></div></section>
<section class="mt-7"><h2 class="mb-3 text-lg font-semibold">Pagamentos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Cliente / título</th><th>Forma</th><th>Referência</th><th>Valor</th><th>Status</th></tr></thead><tbody><tr v-for="item in payments" :key="item.id"><td>{{new Date(item.paid_at).toLocaleString('pt-BR')}}</td><td><p class="font-semibold">{{customer(receivable(item.receivable_id)?.customer_id||'')?.name||'Cliente'}}</p><p class="text-xs text-slate-400">{{receivable(item.receivable_id)?.document_number||'Título financeiro'}}</p></td><td>{{paymentOrigin(item)}}</td><td class="text-xs">{{item.external_id}}</td><td class="font-semibold">{{money(item.amount)}}</td><td><StatusBadge :status="item.status"/></td></tr><tr v-if="!payments.length"><td colspan="6" class="py-10 text-center text-slate-400">Nenhum pagamento registrado.</td></tr></tbody></table></div></section>
<ModalDialog :open="modal" title="Registrar pagamento manual" size="lg" @close="modal=false"><form class="space-y-4" @submit.prevent="pay"><div><label class="label">Cliente</label><SearchSelect v-model="form.customer_id" :options="customerOptions" placeholder="Pesquisar cliente" search-placeholder="Nome, CNPJ/CPF, e-mail ou WhatsApp…"/></div><div><label class="label">Conta a receber</label><SearchSelect v-model="form.receivable_id" :options="receivableOptions" placeholder="Selecione o título" search-placeholder="Documento, descrição ou valor…"/></div><div class="grid grid-cols-2 gap-3"><div><label class="label">Valor</label><input v-model="form.amount" type="number" min="0.01" step="0.01" class="input" required/></div><div><label class="label">Data/hora</label><input v-model="form.paid_at" type="datetime-local" class="input" required/></div></div><div><label class="label">Identificador</label><input v-model="form.external_id" class="input" placeholder="MANUAL-2026-0001" required/></div><div><label class="label">Forma</label><SearchSelect v-model="form.payment_method" :options="paymentMethodOptions"/></div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=false">Cancelar</button><button class="btn-primary" :disabled="!form.receivable_id"><HandCoins :size="18"/> Confirmar pagamento</button></div></form></ModalDialog>
</template>
