<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Download, FileUp, Plus, RefreshCw, Search } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import { fetchAllPages } from '../api/pagination'
import type { ApiResponse, Company, Customer, Receivable } from '../types'
import PageHeader from '../components/PageHeader.vue'
import SectionTabs from '../components/SectionTabs.vue'
import DrawerPanel from '../components/DrawerPanel.vue'
import InlineAlert from '../components/InlineAlert.vue'
import StatusBadge from '../components/StatusBadge.vue'
import EmptyState from '../components/EmptyState.vue'
import SearchSelect, { type SearchSelectOption } from '../components/SearchSelect.vue'

interface Agreement{id:string;company_id:string;name:string;provider:string;cnab_layout:string;is_active:boolean}
interface Remittance{id:string;company_id:string;bank_agreement_id:string;sequence:number;layout:string;status:string;sha256:string;record_count:number;total_amount:string;generated_at:string}
interface Return{id:string;company_id:string;bank_code:string;layout:string;filename:string;sha256:string;status:string;event_count:number;summary:Record<string,unknown>;processed_at?:string;last_error?:string;created_at:string}
interface Event{id:string;return_id:string;receivable_id?:string;charge_id?:string;occurrence_code:string;occurrence_description:string;our_number?:string;amount?:string;occurrence_date?:string;status:string;created_at:string}
interface ProviderRemittanceResult{id:string;sequence:number;layout:string;provider:string;provider_mode:string;implemented_modes:string[]}

const tab=ref('remittances'),agreements=ref<Agreement[]>([]),companies=ref<Company[]>([]),customers=ref<Customer[]>([]),receivables=ref<Receivable[]>([]),remittances=ref<Remittance[]>([]),returns=ref<Return[]>([]),events=ref<Event[]>([]),drawer=ref(false),returnDrawer=ref(false),error=ref(''),success=ref(''),file=ref<File|null>(null),downloading=ref(''),titleSearch=ref('')
const form=reactive({bank_agreement_id:'',receivable_ids:[] as string[],company_id:''})
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const companyName=(id:string)=>companies.value.find(x=>x.id===id)?.trade_name||companies.value.find(x=>x.id===id)?.legal_name||'Empresa'
const customerName=(id:string)=>customers.value.find(x=>x.id===id)?.name||'Cliente'
const normalized=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const summaryText=(item:Return)=>{const s=item.summary||{};const parts=[['Liquidado',s.liquidated],['Associado',s.matched],['Não associado',s.unmatched]].filter(([,v])=>Number(v||0)>0).map(([k,v])=>`${k}: ${v}`);return parts.join(' · ')||`${item.event_count} ocorrência(s)`}
const currentAgreement=computed(()=>agreements.value.find(item=>item.id===form.bank_agreement_id))
const eligibleTitles=computed(()=>receivables.value.filter(item=>['OPEN','REGISTERED'].includes(item.status)&&item.company_id===currentAgreement.value?.company_id))
const visibleTitles=computed(()=>{const term=normalized(titleSearch.value.trim());if(!term)return eligibleTitles.value;return eligibleTitles.value.filter(item=>normalized(`${item.document_number} ${item.description} ${item.balance} ${customerName(item.customer_id)} ${customers.value.find(c=>c.id===item.customer_id)?.tax_id||''}`).includes(term))})
const agreementOptions=computed<SearchSelectOption[]>(()=>agreements.value.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name,description:`${companyName(item.company_id)} · ${item.provider} · CNAB ${item.cnab_layout}`,keywords:`${item.name} ${item.provider} ${companyName(item.company_id)} ${item.cnab_layout}`})))
const companyOptions=computed<SearchSelectOption[]>(()=>companies.value.map(item=>({value:item.id,label:item.trade_name||item.legal_name,description:item.tax_id,keywords:`${item.legal_name} ${item.trade_name||''} ${item.tax_id}`})))

async function load(){error.value='';try{const [a,c,cu,r,rm,rt,e]=await Promise.all([api.get<ApiResponse<Agreement[]>>('/v1/bank-agreements'),api.get<ApiResponse<Company[]>>('/v1/companies'),fetchAllPages<Customer>('/v1/customers'),fetchAllPages<Receivable>('/v1/receivables'),api.get<ApiResponse<Remittance[]>>('/v1/cnab/remittances'),api.get<ApiResponse<Return[]>>('/v1/cnab/returns'),api.get<ApiResponse<Event[]>>('/v1/cnab/events')]);agreements.value=a.data.data;companies.value=c.data.data;customers.value=cu;receivables.value=r;remittances.value=rm.data.data;returns.value=rt.data.data;events.value=e.data.data}catch(e){error.value=apiError(e)}}
function openRemittance(){form.bank_agreement_id=agreements.value.find(x=>x.is_active)?.id||'';form.receivable_ids=[];titleSearch.value='';drawer.value=true}
async function downloadRemittance(item:{id:string;sequence?:number;layout?:string}){downloading.value=item.id;error.value='';try{const response=await api.get(`/v1/cnab/remittances/${item.id}/download`,{responseType:'blob'});const href=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=href;anchor.download=`REM-${String(item.sequence||1).padStart(6,'0')}-CNAB${item.layout||'240'}.REM`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(href)}catch(e){error.value=apiError(e)}finally{downloading.value=''}}
async function generate(){error.value='';try{const agreementId=form.bank_agreement_id;const created=(await api.post<ApiResponse<ProviderRemittanceResult>>('/v1/cnab/provider-remittances',{bank_agreement_id:agreementId,receivable_ids:form.receivable_ids})).data.data;drawer.value=false;success.value=created.provider_mode==='PROVIDER_CNAB'?`Remessa ${created.provider} gerada pelo driver CNAB específico.`:'Remessa CNAB gerada pelo modo legado compatível.';await load();await downloadRemittance({id:created.id,sequence:created.sequence,layout:created.layout||agreements.value.find(x=>x.id===agreementId)?.cnab_layout})}catch(e){error.value=apiError(e)}}
function openReturn(){form.company_id=agreements.value[0]?.company_id||companies.value[0]?.id||'';file.value=null;returnDrawer.value=true}
async function upload(){if(!file.value)return;const data=new FormData();data.append('file',file.value);error.value='';try{await api.post('/v1/cnab/returns',data,{params:{company_id:form.company_id},headers:{'Content-Type':'multipart/form-data'}});returnDrawer.value=false;success.value='Retorno processado e aplicado.';await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>

<template>
<PageHeader title="CNAB 240 e 400" subtitle="Remessas, retornos e ocorrências bancárias em um único lugar."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-secondary" @click="openReturn"><FileUp :size="18"/>Importar retorno</button><button class="btn-primary" @click="openRemittance"><Plus :size="18"/>Gerar remessa</button></PageHeader>
<InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/><SectionTabs v-model="tab" :items="[{key:'remittances',label:'Remessas',count:remittances.length},{key:'returns',label:'Retornos',count:returns.length},{key:'events',label:'Ocorrências',count:events.length}]"/>
<div v-if="tab==='remittances'" class="table-wrap"><table class="table"><thead><tr><th>Sequência</th><th>Convênio</th><th>Layout</th><th>Títulos</th><th>Total</th><th>Status</th><th>Gerada</th><th>Arquivo</th></tr></thead><tbody><tr v-for="item in remittances" :key="item.id" class="border-t border-slate-100"><td class="font-mono font-semibold">{{String(item.sequence).padStart(6,'0')}}</td><td>{{agreements.find(x=>x.id===item.bank_agreement_id)?.name||'Convênio'}}</td><td>CNAB {{item.layout}}</td><td>{{item.record_count}}</td><td class="font-bold">{{money(item.total_amount)}}</td><td><StatusBadge :status="item.status"/></td><td>{{new Date(item.generated_at).toLocaleString('pt-BR')}}</td><td><button class="btn-secondary px-3 py-2" :disabled="downloading===item.id" @click="downloadRemittance(item)"><Download :size="15"/>{{downloading===item.id?'Baixando…':'Baixar'}}</button></td></tr></tbody></table><EmptyState v-if="!remittances.length" title="Nenhuma remessa"/></div>
<div v-else-if="tab==='returns'" class="table-wrap"><table class="table"><thead><tr><th>Arquivo</th><th>Empresa</th><th>Banco</th><th>Layout</th><th>Eventos</th><th>Resultado</th><th>Status</th></tr></thead><tbody><tr v-for="item in returns" :key="item.id" class="border-t border-slate-100"><td><p class="font-semibold">{{item.filename}}</p></td><td>{{companyName(item.company_id)}}</td><td>{{item.bank_code}}</td><td>CNAB {{item.layout}}</td><td>{{item.event_count}}</td><td class="text-xs text-slate-500">{{summaryText(item)}}</td><td><StatusBadge :status="item.status"/><p v-if="item.last_error" class="text-xs text-rose-600">Falha ao processar parte do retorno.</p></td></tr></tbody></table></div>
<div v-else class="table-wrap"><table class="table"><thead><tr><th>Ocorrência</th><th>Nosso número</th><th>Recebível</th><th>Valor</th><th>Data</th><th>Status</th></tr></thead><tbody><tr v-for="item in events" :key="item.id" class="border-t border-slate-100"><td><span class="badge bg-slate-100 text-slate-700">{{item.occurrence_code}}</span><p class="mt-1 text-xs">{{item.occurrence_description}}</p></td><td class="font-mono text-xs">{{item.our_number||'—'}}</td><td class="text-xs">{{item.receivable_id?'Associado':'Não associado'}}</td><td>{{item.amount?money(item.amount):'—'}}</td><td>{{item.occurrence_date?new Date(item.occurrence_date+'T00:00:00').toLocaleDateString('pt-BR'):'—'}}</td><td><StatusBadge :status="item.status"/></td></tr></tbody></table></div>

<DrawerPanel :open="drawer" title="Gerar remessa CNAB" width="lg" @close="drawer=false"><form class="space-y-4" @submit.prevent="generate"><div><label class="label">Convênio</label><SearchSelect v-model="form.bank_agreement_id" :options="agreementOptions" placeholder="Pesquisar convênio" search-placeholder="Convênio, provider, empresa ou layout…"/></div><div v-if="currentAgreement" class="rounded-xl bg-sky-50 p-3 text-xs text-sky-800">Provider: <strong>{{currentAgreement.provider}}</strong> · CNAB {{currentAgreement.cnab_layout}}. Quando houver driver CNAB específico homologável, ele é aplicado automaticamente; caso contrário, o fluxo legado permanece compatível.</div><div><div class="mb-2 flex flex-wrap items-end justify-between gap-2"><label class="label !mb-0">Títulos</label><div class="relative w-full sm:w-72"><Search :size="15" class="absolute left-3 top-2.5 text-slate-400"/><input v-model="titleSearch" class="input !py-2 pl-9" placeholder="Cliente, CNPJ, título ou valor…"/></div></div><div class="scroll-clean max-h-80 space-y-1 overflow-auto rounded-xl border border-slate-200 p-2"><label v-for="r in visibleTitles" :key="r.id" class="flex items-center gap-3 rounded-lg p-2 hover:bg-slate-50"><input v-model="form.receivable_ids" type="checkbox" :value="r.id"/><span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{{customerName(r.customer_id)}} · {{r.document_number}}</span><span class="text-xs text-slate-400">{{r.description}} · vence {{new Date(r.due_date+'T00:00:00').toLocaleDateString('pt-BR')}}</span></span><strong>{{money(r.balance)}}</strong></label><p v-if="!visibleTitles.length" class="p-5 text-center text-sm text-slate-400">Nenhum título elegível para a pesquisa atual.</p></div></div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="drawer=false">Cancelar</button><button class="btn-primary" :disabled="!form.bank_agreement_id||!form.receivable_ids.length"><Download :size="16"/>Gerar e baixar</button></div></form></DrawerPanel>

<DrawerPanel :open="returnDrawer" title="Importar retorno CNAB" width="md" @close="returnDrawer=false"><form class="space-y-4" @submit.prevent="upload"><div><label class="label">Empresa</label><SearchSelect v-model="form.company_id" :options="companyOptions" search-placeholder="Pesquisar empresa ou CNPJ…"/></div><div><label class="label">Arquivo de retorno</label><input type="file" class="input" accept=".ret,.txt,.cnab" required @change="file=($event.target as HTMLInputElement).files?.[0]||null"/></div><div class="rounded-xl bg-sky-50 p-3 text-xs text-sky-800">O sistema identifica automaticamente o layout e aplica as ocorrências aos títulos correspondentes.</div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="returnDrawer=false">Cancelar</button><button class="btn-primary" :disabled="!form.company_id">Processar retorno</button></div></form></DrawerPanel>
</template>
