<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Ban, Copy, Plus, RefreshCw, RotateCw, Send } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import { fetchAllPages } from '../api/pagination'
import type { ApiResponse, Company, Contract, Customer, Receivable } from '../types'
import PageHeader from '../components/PageHeader.vue'
import DrawerPanel from '../components/DrawerPanel.vue'
import InlineAlert from '../components/InlineAlert.vue'
import StatusBadge from '../components/StatusBadge.vue'
import EmptyState from '../components/EmptyState.vue'
import CopyButton from '../components/CopyButton.vue'
import SearchSelect, { type SearchSelectOption } from '../components/SearchSelect.vue'

interface Agreement{id:string;company_id:string;name:string;provider:string;is_active:boolean}
interface Mandate{id:string;company_id:string;customer_id:string;contract_id?:string;bank_agreement_id:string;provider:string;external_id:string;frequency:string;start_date:string;finish_date?:string;fixed_amount?:string;min_limit_value?:string;description:string;payment_creation_mode:string;retry_policy:string;status:string;authorization_url?:string;qr_copy_paste?:string;qr_encoded_image?:string;activated_at?:string;cancelled_at?:string;last_synced_at?:string;last_error?:string;created_at:string}
interface Instruction{id:string;mandate_id:string;receivable_id?:string;charge_id?:string;provider:string;external_id:string;due_date:string;amount:string;status:string;retry_count:number;last_attempt_at?:string;last_error?:string}

const items=ref<Mandate[]>([]),companies=ref<Company[]>([]),customers=ref<Customer[]>([]),contracts=ref<Contract[]>([]),agreements=ref<Agreement[]>([]),receivables=ref<Receivable[]>([]),instructions=ref<Instruction[]>([]),drawer=ref(false),instructionDrawer=ref(false),current=ref<Mandate|null>(null),error=ref(''),success=ref('')
const today=new Date().toISOString().slice(0,10)
const form=reactive({company_id:'',customer_id:'',contract_id:'',bank_agreement_id:'',frequency:'MONTHLY',start_date:today,finish_date:'',fixed_amount:'0',min_limit_value:'',description:'Mensalidade recorrente',immediate_amount:'0.01',immediate_due_date:today,payment_creation_mode:'MANUAL',retry_policy:'ALLOW_THREE_IN_SEVEN_DAYS'})
const instruction=reactive({receivable_id:'',due_date:today,amount:'0'})
const money=(v?:string)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const frequencyLabel=(value:string)=>({WEEKLY:'Semanal',MONTHLY:'Mensal',QUARTERLY:'Trimestral',SEMIANNUALLY:'Semestral',ANNUALLY:'Anual'}[value]||value)
const customer=(id:string)=>customers.value.find(item=>item.id===id)

const companyOptions=computed<SearchSelectOption[]>(()=>companies.value.map(item=>({value:item.id,label:item.trade_name||item.legal_name,description:item.tax_id,keywords:`${item.legal_name} ${item.trade_name||''} ${item.tax_id}`})))
const customerOptions=computed<SearchSelectOption[]>(()=>customers.value.map(item=>({value:item.id,label:item.name,description:item.tax_id||item.trade_name||'',keywords:`${item.name} ${item.trade_name||''} ${item.tax_id||''} ${item.email||''} ${item.whatsapp||''}`})))
const agreementOptions=computed<SearchSelectOption[]>(()=>agreements.value.filter(item=>item.company_id===form.company_id&&item.is_active).map(item=>({value:item.id,label:item.name,description:'Convênio ativo',keywords:item.name})))
const contractOptions=computed<SearchSelectOption[]>(()=>[
  {value:'',label:'Sem contrato',description:'Autorização avulsa'},
  ...contracts.value.filter(item=>item.company_id===form.company_id&&item.customer_id===form.customer_id).map(item=>({value:item.id,label:item.code,description:`${money(item.amount)} · ${frequencyLabel(item.frequency)}`,keywords:`${item.code} ${item.amount} ${item.frequency}`}))
])
const instructionReceivableOptions=computed<SearchSelectOption[]>(()=>{
  if(!current.value)return[{value:'',label:'Sem conta a receber vinculada'}]
  return [
    {value:'',label:'Sem conta a receber vinculada'},
    ...receivables.value.filter(item=>item.company_id===current.value?.company_id&&item.customer_id===current.value?.customer_id&&!['PAID','CANCELLED','REVERSED'].includes(item.status)).map(item=>({value:item.id,label:`${item.document_number} · ${money(item.balance)}`,description:`Vence ${new Date(item.due_date+'T00:00:00').toLocaleDateString('pt-BR')}`,keywords:`${item.document_number} ${item.description} ${item.balance}`}))
  ]
})
const frequencyOptions:SearchSelectOption[]=[{value:'WEEKLY',label:'Semanal'},{value:'MONTHLY',label:'Mensal'},{value:'QUARTERLY',label:'Trimestral'},{value:'SEMIANNUALLY',label:'Semestral'},{value:'ANNUALLY',label:'Anual'}]
const creationModeOptions:SearchSelectOption[]=[{value:'MANUAL',label:'Sob demanda',description:'A cobrança periódica é criada quando solicitada.'},{value:'SUBSCRIPTION',label:'Automática',description:'A plataforma cria as cobranças conforme a autorização.'}]
const retryOptions:SearchSelectOption[]=[{value:'NOT_ALLOWED',label:'Não realizar retentativas'},{value:'ALLOW_THREE_IN_SEVEN_DAYS',label:'Até 3 tentativas em 7 dias'}]

async function load(){error.value='';try{const [m,c,cu,co,a,r]=await Promise.all([api.get<ApiResponse<Mandate[]>>('/v1/pix-automatic/mandates'),api.get<ApiResponse<Company[]>>('/v1/companies'),fetchAllPages<Customer>('/v1/customers'),fetchAllPages<Contract>('/v1/contracts'),api.get<ApiResponse<Agreement[]>>('/v1/bank-agreements'),fetchAllPages<Receivable>('/v1/receivables')]);items.value=m.data.data;companies.value=c.data.data;customers.value=cu;contracts.value=co;agreements.value=a.data.data;receivables.value=r}catch(e){error.value=apiError(e)}}
function open(){const company=companies.value[0];Object.assign(form,{company_id:company?.id||'',customer_id:'',contract_id:'',bank_agreement_id:'',frequency:'MONTHLY',start_date:today,finish_date:'',fixed_amount:'0',min_limit_value:'',description:'Mensalidade recorrente',immediate_amount:'0.01',immediate_due_date:today,payment_creation_mode:'MANUAL',retry_policy:'ALLOW_THREE_IN_SEVEN_DAYS'});drawer.value=true}
async function create(){error.value='';try{await api.post('/v1/pix-automatic/mandates',{...form,contract_id:form.contract_id||null,finish_date:form.finish_date||null,fixed_amount:form.fixed_amount?Number(form.fixed_amount):null,min_limit_value:form.min_limit_value?Number(form.min_limit_value):null,immediate_amount:Number(form.immediate_amount)});drawer.value=false;success.value='Autorização criada. Envie o link ou QR Code ao pagador.';await load()}catch(e){error.value=apiError(e)}}
async function sync(item:Mandate){try{await api.post(`/v1/pix-automatic/mandates/${item.id}/sync`);await load()}catch(e){error.value=apiError(e)}}
async function cancel(item:Mandate){if(!confirm('Cancelar esta autorização Pix Automático?'))return;try{await api.post(`/v1/pix-automatic/mandates/${item.id}/cancel`);await load()}catch(e){error.value=apiError(e)}}
async function viewInstructions(item:Mandate){current.value=item;instructions.value=(await api.get<ApiResponse<Instruction[]>>(`/v1/pix-automatic/mandates/${item.id}/instructions`)).data.data;instruction.amount=item.fixed_amount||'0';instruction.due_date=today;instruction.receivable_id='';instructionDrawer.value=true}
async function createInstruction(){if(!current.value)return;try{await api.post(`/v1/pix-automatic/mandates/${current.value.id}/instructions`,{receivable_id:instruction.receivable_id||null,due_date:instruction.due_date,amount:Number(instruction.amount)});await viewInstructions(current.value);success.value='Cobrança periódica criada.'}catch(e){error.value=apiError(e)}}
watch(()=>form.company_id,()=>{if(!agreementOptions.value.some(option=>option.value===form.bank_agreement_id))form.bank_agreement_id=agreementOptions.value[0]?.value||'';if(form.contract_id&&!contractOptions.value.some(option=>option.value===form.contract_id))form.contract_id=''})
watch(()=>form.customer_id,()=>{if(form.contract_id&&!contractOptions.value.some(option=>option.value===form.contract_id))form.contract_id=''})
onMounted(load)
</script>

<template>
<PageHeader title="Pix Automático" subtitle="Autorizações recorrentes, cobranças periódicas e retentativas controladas."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-primary" @click="open"><Plus :size="18"/>Nova autorização</button></PageHeader>
<InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/>
<div class="grid gap-5 xl:grid-cols-2"><article v-for="item in items" :key="item.id" class="card"><div class="flex items-start gap-3"><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold">{{item.description}}</h2><StatusBadge :status="item.status"/></div><p class="mt-1 text-xs text-slate-400">{{customer(item.customer_id)?.name||'Cliente'}} · Autorização Pix Automático</p></div><button class="btn-secondary px-3 py-2" title="Sincronizar" @click="sync(item)"><RotateCw :size="16"/></button><button v-if="!['CANCELLED','EXPIRED'].includes(item.status)" class="btn-secondary px-3 py-2 text-rose-600" title="Cancelar" @click="cancel(item)"><Ban :size="16"/></button></div><div class="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Frequência</p><p class="font-semibold">{{frequencyLabel(item.frequency)}}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Valor</p><p class="font-semibold">{{money(item.fixed_amount||item.min_limit_value)}}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Início</p><p class="font-semibold">{{new Date(item.start_date+'T00:00:00').toLocaleDateString('pt-BR')}}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Última sincronização</p><p class="font-semibold">{{item.last_synced_at?new Date(item.last_synced_at).toLocaleDateString('pt-BR'):'—'}}</p></div></div><div v-if="item.authorization_url||item.qr_copy_paste" class="mt-4 rounded-xl border border-teal-100 bg-teal-50 p-3"><p class="text-xs font-semibold uppercase text-teal-700">Autorização do pagador</p><div class="mt-2 flex flex-wrap gap-2"><a v-if="item.authorization_url" class="btn-primary px-3 py-2" :href="item.authorization_url" target="_blank" rel="noopener"><Send :size="15"/>Abrir link</a><CopyButton v-if="item.authorization_url" :value="item.authorization_url" label="Copiar link" compact/><CopyButton v-if="item.qr_copy_paste" :value="item.qr_copy_paste" label="Copiar QR" compact/></div></div><p v-if="item.last_error" class="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">Não foi possível sincronizar a autorização. Tente novamente.</p><div class="mt-4 flex justify-end"><button class="btn-secondary" @click="viewInstructions(item)"><Copy :size="16"/>Cobranças periódicas</button></div></article><EmptyState v-if="!items.length" title="Nenhuma autorização Pix Automático" description="Crie uma autorização para cobrança recorrente com consentimento único do pagador."/></div>

<DrawerPanel :open="drawer" title="Nova autorização Pix Automático" width="xl" @close="drawer=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="create"><div><label class="label">Empresa emissora</label><SearchSelect v-model="form.company_id" :options="companyOptions" search-placeholder="Pesquisar empresa ou CNPJ…"/></div><div><label class="label">Convênio</label><SearchSelect v-model="form.bank_agreement_id" :options="agreementOptions" placeholder="Pesquisar convênio" search-placeholder="Pesquisar convênio…"/></div><div><label class="label">Cliente</label><SearchSelect v-model="form.customer_id" :options="customerOptions" placeholder="Pesquisar cliente" search-placeholder="Nome, CNPJ/CPF, e-mail ou WhatsApp…"/></div><div><label class="label">Contrato opcional</label><SearchSelect v-model="form.contract_id" :options="contractOptions" search-placeholder="Pesquisar contrato…"/></div><div class="md:col-span-2"><label class="label">Descrição curta</label><input v-model="form.description" maxlength="35" class="input" required/></div><div><label class="label">Frequência</label><SearchSelect v-model="form.frequency" :options="frequencyOptions"/></div><div><label class="label">Geração da cobrança</label><SearchSelect v-model="form.payment_creation_mode" :options="creationModeOptions"/></div><div><label class="label">Data inicial</label><input v-model="form.start_date" type="date" class="input" required/></div><div><label class="label">Data final</label><input v-model="form.finish_date" type="date" class="input"/></div><div><label class="label">Valor fixo</label><input v-model="form.fixed_amount" type="number" min="0" step="0.01" class="input"/></div><div><label class="label">Limite mínimo variável</label><input v-model="form.min_limit_value" type="number" min="0" step="0.01" class="input"/></div><div><label class="label">Valor inicial</label><input v-model="form.immediate_amount" type="number" min="0.01" step="0.01" class="input" required/></div><div><label class="label">Vencimento inicial</label><input v-model="form.immediate_due_date" type="date" class="input" required/></div><div class="md:col-span-2"><label class="label">Retentativas</label><SearchSelect v-model="form.retry_policy" :options="retryOptions"/></div><div class="md:col-span-2 flex justify-end gap-2 border-t pt-4"><button type="button" class="btn-secondary" @click="drawer=false">Cancelar</button><button class="btn-primary" :disabled="!form.company_id||!form.customer_id||!form.bank_agreement_id">Criar autorização</button></div></form></DrawerPanel>

<DrawerPanel :open="instructionDrawer" title="Cobranças periódicas" width="xl" @close="instructionDrawer=false"><form class="mb-5 grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-4" @submit.prevent="createInstruction"><div><label class="label">Vencimento</label><input v-model="instruction.due_date" type="date" class="input" required/></div><div><label class="label">Valor</label><input v-model="instruction.amount" type="number" min="0.01" step="0.01" class="input" required/></div><div><label class="label">Conta a receber opcional</label><SearchSelect v-model="instruction.receivable_id" :options="instructionReceivableOptions" search-placeholder="Pesquisar título ou valor…"/></div><div class="flex items-end"><button class="btn-primary w-full">Criar cobrança</button></div></form><div class="table-wrap"><table class="table"><thead><tr><th>Vencimento</th><th>Valor</th><th>Tentativas</th><th>Status</th></tr></thead><tbody><tr v-for="item in instructions" :key="item.id" class="border-t border-slate-100"><td>{{new Date(item.due_date+'T00:00:00').toLocaleDateString('pt-BR')}}</td><td class="font-bold">{{money(item.amount)}}</td><td>{{item.retry_count}}</td><td><StatusBadge :status="item.status"/></td></tr></tbody></table></div></DrawerPanel>
</template>
