from __future__ import annotations

from enum import StrEnum


class BankingCapability(StrEnum):
    ACCOUNT_INFO = "ACCOUNT_INFO"
    BALANCE = "BALANCE"
    STATEMENT = "STATEMENT"
    BOLETO_CREATE = "BOLETO_CREATE"
    BOLETO_GET = "BOLETO_GET"
    BOLETO_UPDATE = "BOLETO_UPDATE"
    BOLETO_CANCEL = "BOLETO_CANCEL"
    BOLETO_HYBRID = "BOLETO_HYBRID"
    PIX_COB = "PIX_COB"
    PIX_COBV = "PIX_COBV"
    PIX_RECEIVED = "PIX_RECEIVED"
    PIX_PAYMENT = "PIX_PAYMENT"
    PIX_REFUND = "PIX_REFUND"
    PIX_WEBHOOK = "PIX_WEBHOOK"
    PIX_AUTOMATIC = "PIX_AUTOMATIC"
    PAYMENT_BOLETO = "PAYMENT_BOLETO"
    PAYMENT_TAX = "PAYMENT_TAX"
    PAYMENT_BATCH = "PAYMENT_BATCH"
    TRANSFER_PIX = "TRANSFER_PIX"
    TRANSFER_TED = "TRANSFER_TED"
    DDA = "DDA"
    CNAB_240 = "CNAB_240"
    CNAB_400 = "CNAB_400"
    DIRECT_DEBIT = "DIRECT_DEBIT"
    WEBHOOK = "WEBHOOK"


class BankingIntegrationMode(StrEnum):
    DIRECT_API = "DIRECT_API"
    CNAB = "CNAB"
    OPEN_FINANCE = "OPEN_FINANCE"
    FILE_IMPORT = "FILE_IMPORT"


class BankingEnvironment(StrEnum):
    SANDBOX = "SANDBOX"
    HOMOLOGATION = "HOMOLOGATION"
    PRODUCTION = "PRODUCTION"


class ProviderStatus(StrEnum):
    CATALOG_ONLY = "CATALOG_ONLY"
    DRIVER_SCAFFOLDED = "DRIVER_SCAFFOLDED"
    DRIVER_INSTALLED = "DRIVER_INSTALLED"
    IMPLEMENTED = "IMPLEMENTED"
    SANDBOX_VERIFIED = "SANDBOX_VERIFIED"
    HOMOLOGATION_REQUIRED = "HOMOLOGATION_REQUIRED"
    HOMOLOGATED = "HOMOLOGATED"
    PRODUCTION_READY = "PRODUCTION_READY"
    DEPRECATED = "DEPRECATED"
    DISABLED = "DISABLED"


class BankConnectionStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    CONFIGURED = "CONFIGURED"
    AUTHENTICATING = "AUTHENTICATING"
    CONNECTED = "CONNECTED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    ERROR = "ERROR"
    BLOCKED = "BLOCKED"
    AUTH_ERROR = "AUTH_ERROR"
    CERTIFICATE_EXPIRED = "CERTIFICATE_EXPIRED"
    CERTIFICATE_EXPIRING = "CERTIFICATE_EXPIRING"
    INVALID_CONFIGURATION = "INVALID_CONFIGURATION"
    UNAVAILABLE = "UNAVAILABLE"
    DISCONNECTED = "DISCONNECTED"


class BankingAuthType(StrEnum):
    NONE = "NONE"
    API_KEY = "API_KEY"
    BEARER_TOKEN = "BEARER_TOKEN"
    OAUTH2_CLIENT_CREDENTIALS = "OAUTH2_CLIENT_CREDENTIALS"
    OAUTH2_MTLS = "OAUTH2_MTLS"
    OAUTH2_PRIVATE_KEY_JWT_MTLS = "OAUTH2_PRIVATE_KEY_JWT_MTLS"
    MTLS = "MTLS"
    JWT_CLIENT_ASSERTION = "JWT_CLIENT_ASSERTION"
    JWS = "JWS"
    SIGNED_REQUEST = "SIGNED_REQUEST"
    ECDSA_KEYPAIR = "ECDSA_KEYPAIR"
    CERTIFICATE_AUTH = "CERTIFICATE_AUTH"
    CUSTOM = "CUSTOM"
