CREATE TABLE `TranscriptionJob` (
    `id` VARCHAR(191) NOT NULL,
    `instanceId` VARCHAR(191) NULL,
    `messageId` VARCHAR(191) NULL,
    `sourceKey` VARCHAR(500) NOT NULL,
    `sourceMimeType` VARCHAR(100) NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `model` VARCHAR(100) NOT NULL,
    `language` VARCHAR(16) NULL,
    `status` VARCHAR(20) NOT NULL,
    `text` TEXT NULL,
    `segments` JSON NULL,
    `detectedLanguage` VARCHAR(32) NULL,
    `durationMs` INT NULL,
    `errorCode` VARCHAR(64) NULL,
    `errorMessage` TEXT NULL,
    `attempts` INT NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `startedAt` DATETIME(3) NULL,
    `completedAt` DATETIME(3) NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    INDEX `TranscriptionJob_status_createdAt_idx`(`status`, `createdAt`),
    INDEX `TranscriptionJob_instanceId_createdAt_idx`(`instanceId`, `createdAt`),
    INDEX `TranscriptionJob_messageId_idx`(`messageId`),
    CONSTRAINT `TranscriptionJob_instanceId_fkey` FOREIGN KEY (`instanceId`) REFERENCES `Instance`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `TranscriptionJob_messageId_fkey` FOREIGN KEY (`messageId`) REFERENCES `Message`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
