<script setup lang="ts">
import { onMounted, ref } from 'vue'
import PanelCard from './PanelCard.vue'
import { connect } from '@/services/connect'
import { friendlyError } from '@/services/errors'
const props = defineProps<{ instanceId: string }>(), emit = defineEmits<{ saved: [] }>()
const values = ref<any>(null), error = ref(''), busy = ref(false), feedback = ref('')
onMounted(async () => { try { values.value = await connect.findHubSettings(props.instanceId) } catch(e) { error.value = friendlyError(e) } })
async function save() { busy.value = true; error.value = ''; feedback.value = ''; try { values.value = await connect.findHubSettings(props.instanceId, values.value); feedback.value = 'Parâmetros da conta salvos.'; emit('saved') } catch(e) { error.value = friendlyError(e) } finally { busy.value = false } }
</script>
<template><PanelCard title="Parâmetros de localização" description="Configuração exclusiva desta conta. Não altera mensagens, chamadas ou sessões de outros canais."><div v-if="error" class="alert error">{{ error }}</div><div v-if="feedback" class="alert success">{{ feedback }}</div><form v-if="values" class="form-stack" @submit.prevent="save"><label class="field"><span>Intervalo padrão entre consultas (segundos)</span><input v-model.number="values.intervalSeconds" type="number" min="15" max="86400" required/><small>Aplicado a novos dispositivos. Ajustes individuais podem ser feitos no mapa. Não representa a frequência garantida pelo Google.</small></label><label class="field"><span>Timeout padrão de localização (milissegundos)</span><input v-model.number="values.timeoutMs" type="number" min="5000" max="120000" required/></label><label class="field"><span>Considerar sem atualização após (segundos)</span><input v-model.number="values.staleAfterSeconds" type="number" min="30" max="604800" required/></label><label class="check-row"><input v-model="values.historyEnabled" type="checkbox"/>Armazenar histórico de posições</label><label class="field"><span>Retenção do histórico (dias)</span><input v-model.number="values.retentionDays" type="number" min="0" max="36500" required/><small>0 mantém indefinidamente. A limpeza horária remove lotes de até 1.000 posições antigas somente desta conta. Reduzir esse prazo poderá apagar posições antigas; não há recuperação automática.</small></label><p class="muted">A última posição permanece disponível mesmo com histórico desabilitado. O histórico inicia com os relatórios recebidos após a ativação; não recria movimentações anteriores.</p><button class="btn primary" :disabled="busy">{{ busy ? 'Salvando…' : 'Salvar parâmetros' }}</button></form></PanelCard></template>
