<script setup lang="ts">
import { onMounted, ref } from 'vue'
import PanelCard from './PanelCard.vue'
import { connect } from '@/services/connect'
import { friendlyError } from '@/services/errors'
const props = defineProps<{ instanceId: string; devices: any[]; headerActions?: boolean }>()
const config = ref<any>(null), token = ref(''), chosen = ref(''), error = ref(''), feedback = ref(''), busy = ref(false)
onMounted(async () => { try { config.value = await connect.findHubTraccarConnection(props.instanceId); chosen.value = props.devices[0]?.id || '' } catch(e) { error.value = friendlyError(e) } })
async function save() {
 busy.value = true; error.value = ''; feedback.value = ''
 try { const { mode, url, receiverUrl, timeoutMs } = config.value; config.value = await connect.findHubTraccarConnection(props.instanceId, { mode, ...(mode==='external' ? { url, receiverUrl, ...(token.value ? {token:token.value} : {}) } : {}), timeoutMs }); token.value = ''; feedback.value = 'Conexão Traccar salva.' } catch(e) { error.value = friendlyError(e) } finally { busy.value = false }
}
async function link(remove = false) { busy.value = true; error.value = ''; try { if(remove) await connect.findHubTraccar(props.instanceId,chosen.value,'DELETE'); else await connect.findHubTraccarProvision(props.instanceId,chosen.value); feedback.value = remove ? 'Vínculo removido. O dispositivo remoto foi preservado.' : 'Dispositivo vinculado. Posições serão encaminhadas ao receptor.' } catch(e) { error.value = friendlyError(e) } finally {busy.value = false} }
defineExpose({ save, busy, ready: config })
</script>
<template><PanelCard title="Integração Traccar" description="API oficial e eventos de posições, sem sair da aplicação."><div v-if="error" class="alert error">{{ error }}</div><div v-if="feedback" class="alert success">{{ feedback }}</div><form v-if="config" class="form-stack" @submit.prevent="save"><div v-if="!config.available" class="alert">Traccar desabilitado no deploy. O mapa e o rastreamento Google continuam independentes.</div><label class="field"><span>Modo de operação</span><select v-model="config.mode" class="select"><option value="disabled">Desabilitado</option><option value="internal" :disabled="!config.internalAvailable">Traccar interno</option><option value="external" :disabled="!config.available">Traccar externo</option></select></label><p v-if="config.mode==='internal'" class="muted">O endereço e as credenciais são resolvidos pela rede interna da stack. Nenhuma URL precisa ser informada.</p><template v-if="config.mode==='external'"><label class="field"><span>URL da API Traccar</span><input v-model="config.url" type="url" required placeholder="https://traccar.exemplo.com"/></label><label class="field"><span>URL HTTPS do receptor OsmAnd</span><input v-model="config.receiverUrl" type="url" required placeholder="https://receptor.exemplo.com"/><small>Não é a API administrativa. As duas origens devem ser autorizadas pelo administrador em TRACCAR_ALLOWED_ORIGINS.</small></label><label class="field"><span>Token Traccar</span><input v-model="token" type="password" autocomplete="new-password" :placeholder="config.hasToken ? 'Token protegido — deixe vazio para manter' : 'Informe o token'"/></label></template><label v-if="config.mode!=='disabled'" class="field"><span>Timeout da conexão Traccar (milissegundos)</span><input v-model.number="config.timeoutMs" type="number" min="1000" max="60000"/></label><p class="muted">Alterar o servidor remove somente os vínculos locais para impedir associação a IDs de outro servidor. Histórico e dispositivos remotos são preservados.</p><div v-if="!headerActions" class="toolbar"><button class="btn primary" :disabled="busy">{{ busy ? 'Validando…' : 'Salvar conexão' }}</button></div></form><div v-if="config?.mode!=='disabled' && devices.length" class="form-stack top-gap"><label class="field"><span>Dispositivo desta conta</span><select v-model="chosen" class="select"><option v-for="d in devices" :key="d.id" :value="d.id">{{ d.name }}</option></select></label><div class="toolbar"><button class="btn ghost" :disabled="busy || !chosen" @click="link()">Vincular automaticamente</button><button class="btn ghost" :disabled="busy || !chosen" @click="link(true)">Remover vínculo</button></div><p class="muted">A associação utiliza identificador exclusivo por conta e dispositivo. Credenciais administrativas não são enviadas ao navegador.</p></div></PanelCard></template>
