import type { Logger } from 'zapo-js';
import { type BinaryNode } from 'zapo-js/transport';

import { type AudioSender, EndCallReason, type WaVoipDeps } from '../types.js';
import { type CallInfo } from './call-state.js';
export interface WaCallMediaSessionDelegate {
  emitState(call: CallInfo): void;
  emitIncoming(call: CallInfo): void;
  emitEnded(call: CallInfo): void;
  emitInboundAudio(call: CallInfo, data: Float32Array): void;
  emitInboundVideo?(call: CallInfo, frame: import('../types.js').InboundVideoFrame): void;
  emitVideoKeyFrameRequest?(call: CallInfo): void;
  emitOutboundAudioFinished(call: CallInfo): void;
}
export interface WaCallMediaSessionOptions {
  readonly deps: WaVoipDeps;
  readonly logger: Logger;
  readonly info: CallInfo;
  readonly delegate: WaCallMediaSessionDelegate;
  readonly maxVideoFps?: number;
}
export declare class WaCallMediaSession implements AudioSender {
  readonly info: CallInfo;
  private readonly deps;
  private readonly logger;
  private readonly delegate;
  private rtpSession;
  private srtpSession;
  private opusCodec;
  private readonly sctpRelay;
  private readonly audioEngine;
  private initialTransportSent;
  private outgoingPreacceptSent;
  private selfSsrc;
  private peerSsrcs;
  private firstPacketSent;
  private acceptedByJid;
  private readonly debeEnabled;
  private audioSendCount;
  private audioDropCount;
  private realAudioSendCount;
  private static readonly EMPTY_BYTES;
  private encodeBufferA;
  private encodeBufferB;
  private encodeBuffer;
  private encodeBufferPos;
  private authPaddingBuffer;
  private audioRecvCount;
  private recvRealCount;
  private recvDtxCount;
  private srtpErrorCount;
  private relayPacketCount;
  private stunResponseCount;
  private selfEchoCount;
  private lastRecvSeq;
  private recvSeqGaps;
  private actualPeerSsrc;
  private ssrcResubscribed;
  constructor(options: WaCallMediaSessionOptions);
  get callId(): string;
  initMedia(selfLid: string, peerJid: string): Promise<void>;
  resetOutgoingFlags(): void;
  acceptCall(): Promise<void>;
  rejectCall(reason?: EndCallReason): Promise<void>;
  endCall(reason?: EndCallReason): Promise<void>;
  setMute(muted: boolean): void;
  loadAudio(audioPath: string): Promise<void>;
  setExternalAudioMode(enabled: boolean): void;
  feedLiveAudio(data: Float32Array): number;
  feedLiveVideo(data: Uint8Array, timestampUs: number): number;
  requestVideoKeyFrame(): boolean;
  getLiveBufferMs(): number;
  sendIncomingPreaccept(peerJid: string): Promise<void>;
  sendIncomingRelayLatency(): Promise<void>;
  handleCallAccept(node: BinaryNode, peerJid: string): Promise<void>;
  handleCallPreaccept(node: BinaryNode, peerJid: string): Promise<void>;
  handleCallTransport(_node: BinaryNode): Promise<void>;
  handleCallAck(node: BinaryNode): Promise<void>;
  handleCallRelaylatency(node: BinaryNode, peerJid: string): Promise<void>;
  handleRelayElection(node: BinaryNode): void;
  handleCallMuteV2(node: BinaryNode, peerJid: string): Promise<void>;
  handleCallTerminate(): void;
  sendCapturedAudio(data: Float32Array): void;
  cleanup(): void;
  private get encodeFrameSamples();
  private get rtpTsDelta();
  private sendOpusFrame;
  private ensureDeviceJid;
  private initSrtpKeys;
  private resetEncodeState;
  private onRelayConnected;
  private onRelayData;
  private connectRelays;
  private startMediaFlow;
}
